version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: p0stgreS
      POSTGRES_USER: dev
      POSTGRES_DB: ms_product_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ms_product_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: